name: Test Workflow

on: push

jobs:
  setVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: "6.0.x"
      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.1
      - run: |
          echo "FullSemVer (env.fullSemVer): ${{ env.fullSemVer }}"
